### ISSUE TITLE
After upgrading Unity from 2021.3.16f to 2022.3.19f tiles are blurry and I can't edit rules anymore

### ISSUE THREAD

**Issue by WegPast** [Vinark117/BetterRuleTiles-Support#11]
# Hello !

### Found a new issue after upgrading my Unity editor : 
![image](https://github.com/Vinark117/BetterRuleTiles-Support/assets/9842726/a7965bc7-31a7-423f-8f18-efdaeffd4603)

Tilemap made with Better Rule tiles are all blurry and when I try to open BetterRuleTile Container, I got this error : 
```csharp
Exception thrown while invoking [OnOpenAssetAttribute] method 'VinToolsEditor.BetterRuleTiles.BetterRuleTileAssetHandler:OpenCustomEditorWindow (int,int)' : InvalidCastException: Specified cast is not valid.
VinToolsEditor.BetterRuleTiles.EditorGridBase.FixMissingTexture (UnityEngine.Texture2D tex) (at ./Packages/BetterRuleTiles/Editor/EditorSubClasses/EditorGridBase.cs:505)
VinToolsEditor.BetterRuleTiles.EditorGridBase.CacheSprite (UnityEngine.Sprite sprite) (at ./Packages/BetterRuleTiles/Editor/EditorSubClasses/EditorGridBase.cs:475)
VinToolsEditor.BetterRuleTiles.EditorGridBase.SetUpClass (VinToolsEditor.BetterRuleTiles.BetterRuleTileEditor window, System.Boolean _new) (at ./Packages/BetterRuleTiles/Editor/EditorSubClasses/EditorGridBase.cs:46)
VinToolsEditor.BetterRuleTiles.EditorGridBase..ctor (VinToolsEditor.BetterRuleTiles.BetterRuleTileEditor window, System.Boolean _new) (at ./Packages/BetterRuleTiles/Editor/EditorSubClasses/EditorGridBase.cs:18)
VinToolsEditor.BetterRuleTiles.BetterRuleTileEditor.SetupGrid (System.Boolean _new) (at ./Packages/BetterRuleTiles/Editor/CustomEditor/BetterRuleTileEditor.cs:218)
VinToolsEditor.BetterRuleTiles.BetterRuleTileEditor.ShowWindow (VinTools.BetterRuleTiles.BetterRuleTileContainer container) (at ./Packages/BetterRuleTiles/Editor/CustomEditor/BetterRuleTileEditor.cs:40)
VinToolsEditor.BetterRuleTiles.BetterRuleTileAssetHandler.OpenCustomEditorWindow (System.Int32 instanceID, System.Int32 line) (at ./Packages/BetterRuleTiles/Editor/AssetHandling/BetterRuleTileAssetHandler.cs:20)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)
```
If we follow the the trail to `InvalidCastException: Specified cast is not valid` we got to the `FixMissingTexture` method. And I think it where to look. If I reimport my tileset (the Texture2D generated with BTR) my tiles are not blurry anymore. But if I enter play mode, it become blurry again. If a comment the content of `FixMissingTexture` I can open the BTR container but all are purple and black squares : 

![image](https://github.com/Vinark117/BetterRuleTiles-Support/assets/9842726/199d9295-f5af-4b4b-a107-ee205716a180)

I'm using version 1.4.3

Any idea ?

**Comment by WegPast** [comment]
Hum... please help ?

**Comment by Vinark117** [comment]
The method witch is causing the error is meant to enable read/write on the textures, so the scripts can read and display the textures. Normally this method would only be called the first time you add the sprites to the editor window if they're not readable, but after that they should stay readable and this method would not be called. If this process fails for some reason that's when you'll see the missing textures, which is just a fallback in case the texture can't be read.

I think the problem here is the import settings on the sprites, would you send a screenshot on how you set up the settings on your texture, so I can try replicating the issue?

Here's how I usually set up the texture settings, for reference:

![Unity_iOi8UD9vW9](https://github.com/Vinark117/BetterRuleTiles-Support/assets/76649065/339e8296-8aaf-4967-bd5e-18340eba5c56)

**Comment by WegPast** [comment]
Hi @Vinark117 !
Thank for your answer !
So, I've played around with the "Read/Write" options and the bug disappeared.
But for more precision : my sprite was already read/write enabled. But when I enabled read/write on the sprite Atlas and Tile-set, the bug disappear. So maybe the editor upgrade I've done messed around with those setting...
I'm not with my PC right now, I'll send you more info, if you want, tonight (9:50 am here).

**Comment by WegPast** [comment]
Hey there, sorry for the wait, here is a screenshot of my texture2D settings : 
![image](https://github.com/Vinark117/BetterRuleTiles-Support/assets/9842726/b665280f-9818-48bf-897b-6fc51e35c3ba)

The problem didn't came back so it was a "readable" problem for sure.

Here is my Main Atlas Sprite settings : 
![image](https://github.com/Vinark117/BetterRuleTiles-Support/assets/9842726/a7a939f9-94d4-4f9e-9e4b-39e208809031)

And surprisingly my sprites sources files (made with Aseprite) have now a detailed inspector view... Maybe Unity 2022.3 manage those sprites differently...
![image](https://github.com/Vinark117/BetterRuleTiles-Support/assets/9842726/616f8c28-b05b-4618-bff0-46311fc42cf7)

Anyway thanks for the help. If you need more info/screenshot if you want to replicate, do not hesitate !
Bye !
