### ISSUE TITLE
Improve the neighbor search algorithm to avoid unnecessary logic checks.

### ISSUE THREAD

**Issue by AliMusllam** [Vinark117/BetterRuleTiles-Support#15]
In a 200,000 run time tile generation benchmark, it shows a big difference in speed between **Better rule tiles** and **Unity's basic rule tiles**:

**Better rule** : `` 39510 milliseconds ``
**Unity's rule tile**: `` 16020 milliseconds ``

These generated at run time via `` tileMap.SetTile(pos, tile)  ``

Although both have the same basic setup and neighbor checks. This is mostly because of the extra feature that rules tiles give. 

The request is, to avoid unnecessary logic checks when applicable, and to optimize the logic as much as possible.

**Comment by Vinark117** [comment]
I've did some optimization and testing, and I'm happy to say I did manage to almost double the performance of the better rule tiles.

Here are the test results:

| Name       | Information                                                                                 | Generation time | Relative time |
| ---------- | ------------------------------------------------------------------------------------------- | --------------- | ------------- |
| About test | Initial testing, no changes                                                                 |                 |               |
| Test date  | 08/03/2024 17:10:13                                                                         |                 |               |
| Test size  | 300 x 300                                                                                   |                 |               |
| Default    | Regular rule tile                                                                           | 7.377s          | 100.00%       |
| Simplify   | Simpified rules with better rule tiles (Example 1)                                          | 28.431s         | 385.38%       |
| Advanced   | Regular better rule tiles (Example 2)                                                       | 28.732s         | 389.47%       |
| Variations | This rule uses the variations feature (Example 6)                                           | 28.779s         | 390.10%       |
| Connection | This rule contains data for interactions between other tiles (Example 4)                    | 40.600s         | 550.33%       |
| Properties | This tile uses the custom properties feature and has connections to other tiles (Example 7) | 47.087s         | 638.26%       |

| Name       | Information                                                                                 | Generation time | Relative time |
| ---------- | ------------------------------------------------------------------------------------------- | --------------- | ------------- |
| About test | Added optimization                                                                          |                 |               |
| Test date  | 09/03/2024 13:22:21                                                                         |                 |               |
| Test size  | 300 x 300                                                                                   |                 |               |
| Default    | Regular rule tile                                                                           | 7.138s          | 100.00%       |
| Simplify   | Simpified rules with better rule tiles (Example 1)                                          | 14.239s         | 199.49%       |
| Advanced   | Regular better rule tiles (Example 2)                                                       | 14.304s         | 200.41%       |
| Variations | This rule uses the variations feature (Example 6)                                           | 14.290s         | 200.21%       |
| Connection | This rule contains data for interactions between other tiles (Example 4)                    | 15.051s         | 210.87%       |
| Properties | This tile uses the custom properties feature and has connections to other tiles (Example 7) | 22.294s         | 312.34%       |

These optimizations will be included in the next update.

**Comment by AliMusllam** [comment]
This differently looks promising, a huge difference from previously, thanks for your updates!

**Comment by AliMusllam** [comment]
Thanks for your hard work, I appreciate it :).
I will check it out very soon.
