### ISSUE TITLE
Can't build app because of "The  name 'EditorGUI' does not exist in the current context" error

### ISSUE THREAD

**Issue by WegPast** [Vinark117/BetterRuleTiles-Support#9]
Hi, and thanks for that tool that I recently discovered ! Really nice to have !

But for now I can't build my app because of this error 😟 : 
`\BetterRuleTiles\Editor\Utilities\GUIGrid.cs(77,13): error CS0103: The name 'EditorGUI' does not exist in the current context`

[This post on Itch.io](https://itch.io/post/8299077) pointed it out, but it seems that the problem still here in version 1.4.2

![image](https://github.com/Vinark117/BetterRuleTiles-Support/assets/9842726/33bb1a85-21c0-458e-b6b9-f85dffe9de2c)
![image](https://github.com/Vinark117/BetterRuleTiles-Support/assets/9842726/e3c9e98a-0d42-4d20-842d-1c407b7044b4)
![image](https://github.com/Vinark117/BetterRuleTiles-Support/assets/9842726/9dc8642f-3d8d-4e84-aa46-2e536659dc98)

**Comment by Vinark117** [comment]
Thanks for reporting, I'll fix it immediately. Should expect an update in an hour or so.

**Comment by Vinark117** [comment]
The issue has been fixed and it was uploaded to itch as version 1.4.3, I removed version 1.4.2. Thanks again for reporting the issue, it wouldn't have happened in the first place if I tested building it, but I'll keep that in mind for future updates.
